import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { BRAND } from "@/lib/brand";

/**
 * Generates a real PDF certificate of completion (not a mock). This is
 * intentionally the one piece of "external-looking" functionality that
 * works today with zero configuration, because pdf-lib runs entirely
 * in-process — no network call, no API key, no storage provider required.
 *
 * PROD: once issued, also persist a Certificate row (prisma/schema.prisma)
 * and upload the generated bytes to your storage provider, saving the
 * result's URL to `Certificate.pdfUrl` instead of streaming it inline.
 */
export async function generateCertificatePdf(input: {
  studentName: string;
  courseTitle: string;
  verifyCode: string;
  issuedAt: Date;
}) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([842, 595]); // A4 landscape

  const gold = rgb(0.83, 0.64, 0.29);
  const carbon = rgb(0.06, 0.06, 0.07);
  const bone = rgb(0.12, 0.12, 0.13);

  const serif = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);
  const serifRegular = await pdfDoc.embedFont(StandardFonts.TimesRoman);
  const sans = await pdfDoc.embedFont(StandardFonts.Helvetica);

  page.drawRectangle({ x: 0, y: 0, width: 842, height: 595, color: rgb(0.97, 0.96, 0.94) });
  page.drawRectangle({ x: 24, y: 24, width: 842 - 48, height: 595 - 48, borderColor: gold, borderWidth: 1.5 });
  page.drawRectangle({ x: 34, y: 34, width: 842 - 68, height: 595 - 68, borderColor: gold, borderWidth: 0.5 });

  const centerText = (text: string, y: number, font = serif, size = 20, color = carbon) => {
    const width = font.widthOfTextAtSize(text, size);
    page.drawText(text, { x: (842 - width) / 2, y, size, font, color });
  };

  centerText(BRAND.certificateFooterText, 490, sans, 13, gold);
  centerText("Certificado de Finalización de Formación", 445, serif, 26, carbon);
  centerText("Se certifica que", 395, serifRegular, 13, bone);
  centerText(input.studentName, 355, serif, 30, carbon);
  centerText("completó satisfactoriamente el programa educativo", 310, serifRegular, 13, bone);
  centerText(`"${input.courseTitle}"`, 278, serif, 17, gold);

  const issuedLabel = `Emitido el ${input.issuedAt.toLocaleDateString("es-UY", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })}`;
  centerText(issuedLabel, 220, sans, 10, bone);

  centerText(
    "Este certificado acredita la finalización de una formación educativa online. No constituye",
    170,
    sans,
    8.5,
    bone
  );
  centerText(
    "una certificación profesional oficial ni garantiza aptitud para el ejercicio profesional.",
    158,
    sans,
    8.5,
    bone
  );

  centerText(`Código de verificación: ${input.verifyCode}`, 60, sans, 9, bone);

  return pdfDoc.save();
}
